### ISSUE TITLE
Webpack bundling error caused by `webpack-cli` versioning.

### ISSUE THREAD

**Issue by zourdyzou** [glook/webpack4-react-boilerplate#21]
![Screenshot 2022-06-29 at 05 07 55](https://user-images.githubusercontent.com/69587933/176343130-a54bc36d-c975-4ea9-9fc9-db6dc0387867.png)

I will fix it ASAP.

**Comment by eugbyte** [comment]
Facing the same issue

```
$ npm run start
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.

> webpack-typescript-react@1.0.7 start
> cross-env WEBPACK_IS_DEV_SERVER=true NODE_ENV=development webpack serve --config webpack.config.babel.js

[webpack-cli] TypeError: cli.isMultipleCompiler is not a function
    at Command.<anonymous> (C:\Users\eugen\Codes\personal\sample-project\node_modules\@webpack-cli\serve\lib\index.js:146:35)
    at async Promise.all (index 1)
    at Command.<anonymous> (C:\Users\eugen\Codes\personal\sample-project\node_modules\webpack-cli\lib\webpack-cli.js:1674:7)
```

**Comment by OliverDavey** [comment]
This can be fixed by updating the required version in package.json to "~4.10.0"
